### ISSUE TITLE
底部跳跃的小鱼动画

### ISSUE THREAD

**Issue by leslieyin** [gitldy1013/vuepress-theme-ldy#1]
博主您好，想请教一下，您的主题底部跳跃的小鱼动画，如果我想引用到vuepress其他主题中，该如何操作呢，😉

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by gitldy1013** [comment]
我直接改的引入的js文件 由于私人博客中有日记等个人私密文章 没法提供抱歉  😞 不过你你可以参考我的博客园: https://www.cnblogs.com/ldy-blogs/

**Comment by gitldy1013** [comment]
上面的网站也是参照别人的主题改造的 如果需要js文件 我可以提供给你

**Comment by leslieyin** [comment]
不用啦。感谢！
